[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Common-Utils"
version = "2025.3"
dynamic = ["dependencies"]
requires-python = "==3.12.3"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
